                                                                                                                                                                                                                                                package com.example.mallar.ml

                                                                                                                                                                                                                                                import android.graphics.Bitmap
                                                                                                                                                                                                                                                import android.util.Log
                                                                                                                                                                                                                                                import com.example.mallar.data.GraphNode
                                                                                                                                                                                                                                                import com.example.mallar.data.LandmarkDetection
                                                                                                                                                                                                                                                import com.example.mallar.data.LocalizationResult
                                                                                                                                                                                                                                                import com.example.mallar.data.MallGraph
                                                                                                                                                                                                                                                import com.example.mallar.data.MallGraphRepository
                                                                                                                                                                                                                                                import com.example.mallar.data.Place
                                                                                                                                                                                                                                                import kotlin.math.*

                                                                                                                                                                                                                                                private const val TAG = "LocalizationEngine"

                                                                                                                                                                                                                                                /**
                                                                                                                                                                                                                                                * ─────────────────────────────────────────────────────────────────────────────
                                                                                                                                                                                                                                                * LocalizationEngine  v2  —  Full PnP Pipeline
                                                                                                                                                                                                                                                * ─────────────────────────────────────────────────────────────────────────────
                                                                                                                                                                                                                                                *
                                                                                                                                                                                                                                                * PIPELINE
                                                                                                                                                                                                                                                * --------
                                                                                                                                                                                                                                                *  1. [LogoDetector.detectTopNWithLocation]
                                                                                                                                                                                                                                                *        Runs the embedding model on a 3×3 grid of image crops.
                                                                                                                                                                                                                                                *        Returns up to N DetectionResult objects each carrying:
                                                                                                                                                                                                                                                *          • brand name  • similarity score  • imageX, imageY [0,1]
                                                                                                                                                                                                                                                *
                                                                                                                                                                                                                                                *  2. World-coordinate matching
                                                                                                                                                                                                                                                *        Each brand is mapped to its [GraphNode] in the mall graph.
                                                                                                                                                                                                                                                *        The corridor-side of that node is used (not the store front)
                                                                                                                                                                                                                                                *        because the user stands in the corridor while scanning.
                                                                                                                                                                                                                                                *
                                                                                                                                                                                                                                                *  3. Distance filtering  (via [PnPSolver.estimateDistancePx])
                                                                                                                                                                                                                                                *        Landmarks with implausible estimated distances are rejected.
                                                                                                                                                                                                                                                *        This catches "far away logo barely visible" false positives.
                                                                                                                                                                                                                                                *
                                                                                                                                                                                                                                                *  4. [PnPSolver.solve]  —  Bearing Triangulation
                                                                                                                                                                                                                                                *        For N ≥ 2 landmarks:
                                                                                                                                                                                                                                                *          Scores every corridor graph node within SEARCH_RADIUS by how
                                                                                                                                                                                                                                                *          well it explains the observed image-space bearing angles (αᵢ).
                                                                                                                                                                                                                                                *          Returns best (cameraX, cameraY, headingDeg, reprojectionError).
                                                                                                                                                                                                                                                *        For N = 1 landmark:
                                                                                                                                                                                                                                                *          Falls back to corridor-side snapping (no heading available).
                                                                                                                                                                                                                                                *
                                                                                                                                                                                                                                                *  5. Confidence calculation
                                                                                                                                                                                                                                                *        Blends ML similarity, PnP reprojection error, and landmark count.
                                                                                                                                                                                                                                                *
                                                                                                                                                                                                                                                *  6. [LocalizationResult] returned → consumed by [LocalizationConfirmScreen].
                                                                                                                                                                                                                                                *
                                                                                                                                                                                                                                                * WHY THIS IS BETTER THAN v1
                                                                                                                                                                                                                                                * --------------------------
                                                                                                                                                                                                                                                *  v1: weighted centroid of corridor positions, heading assumed = "face stores"
                                                                                                                                                                                                                                                *  v2: real image-space bearing angles + graph-constrained triangulation.
                                                                                                                                                                                                                                                *      The position and heading come from the same geometric constraint, not
                                                                                                                                                                                                                                                *      independent heuristics.
                                                                                                                                                                                                                                                * ─────────────────────────────────────────────────────────────────────────────
                                                                                                                                                                                                                                                */
                                                                                                                                                                                                                                                object LocalizationEngine {

                                                                                                                                                                                                                                                    // ── Tuneable constants ─────────────────────────────────────────────────────

                                                                                                                                                                                                                                                    private const val MIN_LANDMARK_SIMILARITY   = 0.35f
                                                                                                                                                                                                                                                    private const val MAX_DIST_PX               = 350.0    // reject landmarks further than this
                                                                                                                                                                                                                                                    private const val MIN_DIST_PX               = 5.0     // reject implausibly close landmarks

                                                                                                                                                                                                                                                    // Reprojection error caps used to normalise confidence
                                                                                                                                                                                                                                                    private const val PERFECT_REPROJ_ERR_DEG    = 0f
                                                                                                                                                                                                                                                    private const val WORST_REPROJ_ERR_DEG      = 30f

                                                                                                                                                                                                                                                    // ── Public API ─────────────────────────────────────────────────────────────

                                                                                                                                                                                                                                                    /**
                                                                                                                                                                                                                                                    * Full localization pipeline: detect → match → PnP → confidence.
                                                                                                                                                                                                                                                    *
                                                                                                                                                                                                                                                    * @param frame       Camera frame bitmap.
                                                                                                                                                                                                                                                    * @param detector    Ready [LogoDetector] instance.
                                                                                                                                                                                                                                                    * @param graph       Loaded [MallGraph].
                                                                                                                                                                                                                                                    * @param places      Loaded [Place] list (for logo display in confirmation UI).
                                                                                                                                                                                                                                                    * @param maxLandmarks Max number of brands to detect (default 5).
                                                                                                                                                                                                                                                    */
                                                                                                                                                                                                                                                    fun estimatePose(
                                                                                                                                                                                                                                                        frame:         Bitmap,
                                                                                                                                                                                                                                                        detector:      LogoDetector,
                                                                                                                                                                                                                                                        graph:         MallGraph,
                                                                                                                                                                                                                                                        places:        List<Place>,
                                                                                                                                                                                                                                                        maxLandmarks:  Int = 5
                                                                                                                                                                                                                                                    ): LocalizationResult {

                                                                                                                                                                                                                                                        val frameWidth  = frame.width
                                                                                                                                                                                                                                                        val frameHeight = frame.height

                                                                                                                                                                                                                                                        // ── 1. Detect top-N brands WITH image-space location ──────────────────
                                                                                                                                                                                                                                                        val rawDetections = detector.detectTopNWithLocation(
                                                                                                                                                                                                                                                            bitmap        = frame,
                                                                                                                                                                                                                                                            maxResults    = maxLandmarks,
                                                                                                                                                                                                                                                            minSimilarity = MIN_LANDMARK_SIMILARITY
                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                        Log.d(TAG, "Step 1 — raw detections: ${rawDetections.size}")

                                                                                                                                                                                                                                                        if (rawDetections.isEmpty()) return noDetectionResult()

                                                                                                                                                                                                                                                        // ── 2. Match to world coordinates ─────────────────────────────────────
                                                                                                                                                                                                                                                        val intrinsics = CameraIntrinsics.estimate(frameWidth, frameHeight)

                                                                                                                                                                                                                                                        data class MatchedLandmark(
                                                                                                                                                                                                                                                            val detection: DetectionResult,
                                                                                                                                                                                                                                                            val graphNode: GraphNode,
                                                                                                                                                                                                                                                            val worldPos:  Pair<Double, Double>,   // corridor-side world (x, y)
                                                                                                                                                                                                                                                            val place:     Place?,
                                                                                                                                                                                                                                                            val estimatedDistPx: Double?
                                                                                                                                                                                                                                                        )

                                                                                                                                                                                                                                                        val matched: List<MatchedLandmark> = rawDetections.mapNotNull { det ->
                                                                                                                                                                                                                                                            val node = findNodeForBrand(graph, det.brand) ?: return@mapNotNull null
                                                                                                                                                                                                                                                            val (wx, wy) = corridorSideOf(node, graph)
                                                                                                                                                                                                                                                            val place = places.firstOrNull { p ->
                                                                                                                                                                                                                                                                p.brand.equals(det.brand, ignoreCase = true) ||
                                                                                                                                                                                                                                                                p.brand.contains(det.brand, ignoreCase = true)
                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                            val dist = PnPSolver.estimateDistancePx(det.imageY, intrinsics, frameHeight)
                                                                                                                                                                                                                                                            MatchedLandmark(det, node, Pair(wx, wy), place, dist)
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                        Log.d(TAG, "Step 2 — matched to graph: ${matched.size}")

                                                                                                                                                                                                                                                        if (matched.isEmpty()) return noDetectionResult()

                                                                                                                                                                                                                                                        // ── 3. Distance filtering ─────────────────────────────────────────────
                                                                                                                                                                                                                                                        val filtered = matched.filter { lm ->
                                                                                                                                                                                                                                                            val d = lm.estimatedDistPx
                                                                                                                                                                                                                                                            if (d == null) {
                                                                                                                                                                                                                                                                // Vertical position doesn't give a valid estimate — keep but flag
                                                                                                                                                                                                                                                                Log.d(TAG, "  ${lm.detection.brand}: dist estimate N/A — kept")
                                                                                                                                                                                                                                                                true
                                                                                                                                                                                                                                                            } else if (d < MIN_DIST_PX || d > MAX_DIST_PX) {
                                                                                                                                                                                                                                                                Log.d(TAG, "  ${lm.detection.brand}: dist=%.0fpx REJECTED (out of range)".format(d))
                                                                                                                                                                                                                                                                false
                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                Log.d(TAG, "  ${lm.detection.brand}: dist=%.0fpx OK".format(d))
                                                                                                                                                                                                                                                                true
                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                        Log.d(TAG, "Step 3 — after distance filter: ${filtered.size}")

                                                                                                                                                                                                                                                        if (filtered.isEmpty()) return noDetectionResult()

                                                                                                                                                                                                                                                        // Build LandmarkDetection list for the result object
                                                                                                                                                                                                                                                        val landmarks: List<LandmarkDetection> = filtered.map { lm ->
                                                                                                                                                                                                                                                            LandmarkDetection(lm.detection.similarity, lm.detection.brand, lm.graphNode, lm.place)
                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                        // ── 4. PnP solve (N ≥ 2) or corridor snap (N = 1) ────────────────────
                                                                                                                                                                                                                                                        return if (filtered.size >= 2) {
                                                                                                                                                                                                                                                            val imagePoints = filtered.map { Pair(it.detection.imageX, it.detection.imageY) }
                                                                                                                                                                                                                                                            val worldPoints = filtered.map { it.worldPos }

                                                                                                                                                                                                                                                            val pnpResult = PnPSolver.solve(imagePoints, worldPoints, intrinsics, graph, frameWidth)

                                                                                                                                                                                                                                                            if (pnpResult != null) {
                                                                                                                                                                                                                                                                buildPnPResult(landmarks, pnpResult, graph)
                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                // PnP solver found no consistent pose — fall back to centroid
                                                                                                                                                                                                                                                                Log.w(TAG, "PnP failed — falling back to centroid")
                                                                                                                                                                                                                                                                centroidFallback(landmarks, graph)
                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                            singleLandmarkFallback(filtered.first().let {
                                                                                                                                                                                                                                                                LandmarkDetection(it.detection.similarity, it.detection.brand, it.graphNode, it.place)
                                                                                                                                                                                                                                                            }, graph)
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                    // ─────────────────────────────────────────────────────────────────────────
                                                                                                                                                                                                                                                    // Result builders
                                                                                                                                                                                                                                                    // ─────────────────────────────────────────────────────────────────────────

                                                                                                                                                                                                                                                    private fun buildPnPResult(
                                                                                                                                                                                                                                                        landmarks:  List<LandmarkDetection>,
                                                                                                                                                                                                                                                        pnp:        PnPSolver.PoseResult,
                                                                                                                                                                                                                                                        graph:      MallGraph
                                                                                                                                                                                                                                                    ): LocalizationResult {
                                                                                                                                                                                                                                                        // Confidence: blend similarity, PnP error, and inlier ratio
                                                                                                                                                                                                                                                        val avgSim      = landmarks.sumOf { it.similarity.toDouble() } / landmarks.size
                                                                                                                                                                                                                                                        val errNorm     = (pnp.reprojectionErrorDeg.toDouble() / WORST_REPROJ_ERR_DEG.toDouble()).coerceIn(0.0, 1.0)
                                                                                                                                                                                                                                                        val inlierRatio = pnp.inlierCount.toDouble() / landmarks.size
                                                                                                                                                                                                                                                        val bonus       = if (landmarks.size >= 3) 0.08 else 0.0

                                                                                                                                                                                                                                                        val confidence = (avgSim * 0.5 + inlierRatio * 0.35 + (1.0 - errNorm) * 0.15 + bonus)
                                                                                                                                                                                                                                                            .toFloat().coerceIn(0f, 1f)

                                                                                                                                                                                                                                                        val reason = buildReason(landmarks.size, pnp, confidence)
                                                                                                                                                                                                                                                        val bestNode = MallGraphRepository.findNearestNode(graph, pnp.cameraX, pnp.cameraY)

                                                                                                                                                                                                                                                        Log.d(TAG, "PnP result: conf=${"%.2f".format(confidence)} heading=${pnp.headingDeg}°")

                                                                                                                                                                                                                                                        return LocalizationResult(
                                                                                                                                                                                                                                                            detections           = landmarks,
                                                                                                                                                                                                                                                            estimatedMapX        = pnp.cameraX,
                                                                                                                                                                                                                                                            estimatedMapY        = pnp.cameraY,
                                                                                                                                                                                                                                                            estimatedHeadingDeg  = pnp.headingDeg,
                                                                                                                                                                                                                                                            confidence           = confidence,
                                                                                                                                                                                                                                                            confidenceReason     = reason,
                                                                                                                                                                                                                                                            bestStartNode        = bestNode
                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                    private fun centroidFallback(
                                                                                                                                                                                                                                                        landmarks: List<LandmarkDetection>,
                                                                                                                                                                                                                                                        graph:     MallGraph
                                                                                                                                                                                                                                                    ): LocalizationResult {
                                                                                                                                                                                                                                                        val (cx, cy) = corridorSideOf(landmarks.first().graphNode, graph)
                                                                                                                                                                                                                                                        val confidence = (landmarks.sumOf { it.similarity.toDouble() } / landmarks.size * 0.55).toFloat()
                                                                                                                                                                                                                                                        val bestNode = MallGraphRepository.findNearestNode(graph, cx, cy)
                                                                                                                                                                                                                                                        return LocalizationResult(
                                                                                                                                                                                                                                                            detections          = landmarks,
                                                                                                                                                                                                                                                            estimatedMapX       = cx,
                                                                                                                                                                                                                                                            estimatedMapY       = cy,
                                                                                                                                                                                                                                                            estimatedHeadingDeg = null,
                                                                                                                                                                                                                                                            confidence          = confidence,
                                                                                                                                                                                                                                                            confidenceReason    = "Position estimated via corridor centroid (PnP inconclusive)",
                                                                                                                                                                                                                                                            bestStartNode       = bestNode
                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                    private fun singleLandmarkFallback(
                                                                                                                                                                                                                                                        lm:    LandmarkDetection,
                                                                                                                                                                                                                                                        graph: MallGraph
                                                                                                                                                                                                                                                    ): LocalizationResult {
                                                                                                                                                                                                                                                        val (cx, cy) = corridorSideOf(lm.graphNode, graph)
                                                                                                                                                                                                                                                        val confidence = (lm.similarity * 0.55f).coerceIn(0f, 1f)
                                                                                                                                                                                                                                                        val bestNode = MallGraphRepository.findNearestNode(graph, cx, cy)
                                                                                                                                                                                                                                                        return LocalizationResult(
                                                                                                                                                                                                                                                            detections          = listOf(lm),
                                                                                                                                                                                                                                                            estimatedMapX       = cx,
                                                                                                                                                                                                                                                            estimatedMapY       = cy,
                                                                                                                                                                                                                                                            estimatedHeadingDeg = null,
                                                                                                                                                                                                                                                            confidence          = confidence,
                                                                                                                                                                                                                                                            confidenceReason    = "1 store detected (${lm.brand}) — single-landmark estimate",
                                                                                                                                                                                                                                                            bestStartNode       = bestNode
                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                    // ─────────────────────────────────────────────────────────────────────────
                                                                                                                                                                                                                                                    // Helpers
                                                                                                                                                                                                                                                    // ─────────────────────────────────────────────────────────────────────────

                                                                                                                                                                                                                                                    private fun findNodeForBrand(graph: MallGraph, brand: String): GraphNode? {
                                                                                                                                                                                                                                                        val norm = brand.trim().lowercase()
                                                                                                                                                                                                                                                        return graph.nodes.firstOrNull { node ->
                                                                                                                                                                                                                                                            val n = node.shopName?.trim()?.lowercase() ?: return@firstOrNull false
                                                                                                                                                                                                                                                            n == norm || n.contains(norm) || norm.contains(n)
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                    /** Returns the corridor-side position in front of a store node. */
                                                                                                                                                                                                                                                    private fun corridorSideOf(node: GraphNode, graph: MallGraph): Pair<Double, Double> {
                                                                                                                                                                                                                                                        val neighbourIds = graph.edges
                                                                                                                                                                                                                                                            .filter { it.from == node.id || it.to == node.id }
                                                                                                                                                                                                                                                            .flatMap  { listOf(it.from, it.to) }
                                                                                                                                                                                                                                                            .filter   { it != node.id }
                                                                                                                                                                                                                                                            .toSet()

                                                                                                                                                                                                                                                        val corridorNeighbours = neighbourIds.mapNotNull { id ->
                                                                                                                                                                                                                                                            graph.nodes.firstOrNull { it.id == id && it.shopId == null }
                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                        return if (corridorNeighbours.isNotEmpty()) {
                                                                                                                                                                                                                                                            val mx = corridorNeighbours.sumOf { it.x } / corridorNeighbours.size.toDouble()
                                                                                                                                                                                                                                                            val my = corridorNeighbours.sumOf { it.y } / corridorNeighbours.size.toDouble()
                                                                                                                                                                                                                                                            Pair(mx, my)
                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                            Pair(node.x, node.y)
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                    private fun buildReason(
                                                                                                                                                                                                                                                        count:      Int,
                                                                                                                                                                                                                                                        pnp:        PnPSolver.PoseResult,
                                                                                                                                                                                                                                                        confidence: Float
                                                                                                                                                                                                                                                    ): String {
                                                                                                                                                                                                                                                        val pct = "%.0f".format(confidence * 100)
                                                                                                                                                                                                                                                        val errStr = "%.1f".format(pnp.reprojectionErrorDeg)
                                                                                                                                                                                                                                                        return when {
                                                                                                                                                                                                                                                            count >= 3 -> "$count landmarks • PnP err=${errStr}° • confidence $pct%"
                                                                                                                                                                                                                                                            count == 2 -> "2 landmarks • PnP err=${errStr}° • confidence $pct%"
                                                                                                                                                                                                                                                            else       -> "1 landmark • corridor snap • confidence $pct%"
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                    private fun noDetectionResult() = LocalizationResult(
                                                                                                                                                                                                                                                        detections          = emptyList(),
                                                                                                                                                                                                                                                        estimatedMapX       = null,
                                                                                                                                                                                                                                                        estimatedMapY       = null,
                                                                                                                                                                                                                                                        estimatedHeadingDeg = null,
                                                                                                                                                                                                                                                        confidence          = 0f,
                                                                                                                                                                                                                                                        confidenceReason    = "No recognisable stores detected",
                                                                                                                                                                                                                                                        bestStartNode       = null
                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                }
